### PR TITLE
Add quotes via npm script

### PR DESCRIPTION
**Pull request by seajee**
Now you can easily add a quote to the database with an npm script. Ready for review

### CODE REVIEW

**Comment by seajee** [comment]
There is a problem with the add.ts script. It's not consistent between addQuote requests, It doesn't always go through.

**Comment by seajee** [comment]
With the latest commit, the script will wait with a callback until the query has finished to process in the backend. This behavior has been tested. Awaiting review

**Review by giopera — APPROVED** [review]
It's ok

**Comment by seajee** [comment]
LGTM!

**Pull request merged**
